/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package satdoku;

import org.sat4j.minisat.SolverFactory;
import org.sat4j.reader.DimacsReader;
import org.sat4j.reader.ParseFormatException;
import org.sat4j.reader.Reader;
import org.sat4j.specs.ContradictionException;
import org.sat4j.specs.IProblem;
import org.sat4j.specs.ISolver;
import org.sat4j.specs.TimeoutException;

import java.io.IOException;
import java.io.PrintWriter;

public class App {
    public static void main(String[] args) throws IOException, ParseFormatException, ContradictionException, TimeoutException {
        ISolver solver = SolverFactory.newDefault();
        solver.setTimeout(60); // one minute
        Reader reader = new DimacsReader(solver);
        PrintWriter out = new PrintWriter(System.out, true);
        IProblem problem = reader.parseInstance(args[0]);
        if (problem.isSatisfiable()) {
            System.out.println("Satisfiable !");
            reader.decode(problem.model(),out);
        } else {
            System.out.println("Unsatisfiable");
        }
    }
}
